# Introduction
Dans ce notebook, vous allez implémenter un arbre de décision binaire à partir de zéro.
Vous utiliserez uniquement des listes Python, sans bibliothèques comme pandas ou numpy.
Un sous-ensemble des données du dataset IRIS est inclus dans ce notebook avec ses quatre caractéristiques.

# Étape 1 : Le dataset
## Créer le dataset
Voici une version complète du dataset IRIS contenant ses quatre caractéristiques :

| Longueur de la pétale | Largeur de la pétale | Longueur de la sépale | Largeur de la sépale | Etiquette |
|-----------------------|----------------------|-----------------------|----------------------|-----------|
| 5.1 | 3.5 | 1.4 | 0.2 | setosa |
| 4.9 | 3.0 | 1.4 | 0.2 | setosa |
| 4.7 | 3.2 | 1.3 | 0.2 | setosa |
| 7.0 | 3.2 | 4.7 | 1.4 | versicolor |
| 6.4 | 3.2 | 4.5 | 1.5 | versicolor |
| 6.9 | 3.1 | 4.9 | 1.5 | versicolor |
| 6.3 | 3.3 | 6.0 | 2.5 | virginica |
| 5.8 | 2.7 | 5.1 | 1.9 | virginica |
| 7.1 | 3.0 | 5.9 | 2.1 | virginica |

Créer une liste de listes permettant de stocker ces données. Chaque liste interne contient un exemple, c'est à dire une ligne du dataset avec les 4 valeurs caractéristiques et l'étiquette. La liste globale contient l'ensemble des exemples du dataset, c'est à dire toutes les lignes du tableau. Stocker cette liste dans une variable

In [2]:
import pandas as pd
dataset = [[5.1,	3.5,	1.4,	0.2,	"setosa"],
           [4.9,	3.0,	1.4,	0.2,	"setosa"],
           [4.7,	3.2,	1.3,	0.2,	"setosa"],
           [7.0,	3.2,	4.7,	1.4,	"versicolor"],
           [6.4,	3.2,	4.5,	1.5, "versicolor"],
           [6.9,	3.1,	4.9,	1.5,	"versicolor"],
           [6.3,	3.3,	6.0,	2.5,	"virginica"],
           [5.8,	2.7,	5.1,	1.9,	"virginica"],
           [7.1,	3.0,	5.9,	2.1,	"virginica"]]
dataset = pd.DataFrame(dataset, columns=["Longueur de la pétale", "Largeur de la pétale", "Longueur de la sépale", "Largeur de la sépale", "Etiquette"])
dataset


Longueur de la pétale  Largeur de la pétale  Longueur de la sépale  \
0                    5.1                   3.5                    1.4   
1                    4.9                   3.0                    1.4   
2                    4.7                   3.2                    1.3   
3                    7.0                   3.2                    4.7   
4                    6.4                   3.2                    4.5   
5                    6.9                   3.1                    4.9   
6                    6.3                   3.3                    6.0   
7                    5.8                   2.7                    5.1   
8                    7.1                   3.0                    5.9   

   Largeur de la sépale   Etiquette  
0                   0.2      setosa  
1                   0.2      setosa  
2                   0.2      setosa  
3                   1.4  versicolor  
4                   1.5  versicolor  
5                   1.5  versicolor  
6                   2.5   virginica  
7                   1.9   virginica  
8                   2.1   virginica

## Préparer les données
Ecrire la fonction `split_data` qui sépare les données en caractéristiques (stockées dans une variable X) et étiquettes (stockées dans une variable y)
Afficher les variables X et y pour valider leur contenu.

In [8]:
def split_data(data):
    X = data.iloc[:, :-1].values
    y = data.iloc[:, -1].values
    return X, y

X, y = split_data(dataset)
print("Caractéristiques (X):")
print(X)
print("\nÉtiquettes (y):")
print(y)

Caractéristiques (X):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]]

Étiquettes (y):
['setosa' 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'virginica']


# Étape 2 : Créer une classe pour représenter un arbre binaire

Créer une classe `BinaryDecisionTree` permettant de définir des règles génériques pour tout arbre binaire.
Cette classe doit contenir:

- une méthode `__init__` qui est le constructeur de la classe. Elle doit permettre d'initialise un nœud de l'arbre de décision avec paramètres suivants:

    - Entrées:
        - `feature_index` : index de la caractéristique utilisée pour la division.
        - `threshold` : valeur seuil pour diviser les données.
        - `left` : sous-arbre gauche.
        - `right` : sous-arbre droit.
        - `value` : valeur de la classe si c'est une feuille (None pour un nœud interne).

- une méthode `is_leaf` qui vérifie si le nœud actuel est une feuille:
    - Sortie:
        - Retourne `True` si le nœud contient une valeur (donc une feuille).
        - Retourne `False` si le nœud est un nœud interne.

- une méthode `predict` qui prédit la classe pour une ligne donnée.
    - Entrée:
        - `row` : liste des caractéristiques d'une instance.
    - Sortie:
        - Si le nœud est une feuille, retourne la valeur de la classe.
        - Sinon, compare la valeur de la caractéristique à l'index `feature_index` avec le seuil.
           - Si inférieur au seuil, appelle récursivement la méthode sur le sous-arbre gauche.
           - Sinon, appelle récursivement la méthode sur le sous-arbre droit.

In [13]:
class BinaryDecisionTree:
  def __init__(self, feature_index = None, threshold = None, left = None, right = None, value = None):
    self.feature_index = feature_index
    self.threshold = threshold
    self.left = left
    self.right = right
    self.value = value

  def is_leaf(self):
    if self.value == None:
      return False
    return True

  def predict(self,row):
    if self.is_leaf():
      return self.value
    else:
      if row[self.feature_index] < self.threshold:
        return self.left.predict(row)

      return self.right.predict(row)

# Etape 3 : Créer une fonction pour construire un arbre facilement
Ecrire la fonction `build_tree` qui permet de construire un arbre de décision binaire spécifique pour le dataset IRIS.
    
    - Sortie:
        - Retourne la racine de l'arbre construit.

    - Description de l'arbre :
        - À la racine, on utilise la caractéristique 0 (longueur des sépales) avec un seuil de 6.0.
            - Si inférieur à 6.0 :
                - On utilise la caractéristique 1 (largeur des sépales) avec un seuil de 3.0.
                    - Si inférieur à 3.0 :
                        - On utilise la caractéristique 2 (longueur des pétales) avec un seuil de 4.5.
                            - Si inférieur à 4.5 : classe "setosa".
                            - Sinon : classe "versicolor".
                    - Sinon : classe "versicolor".
            - Sinon :
                - On utilise la caractéristique 2 (longueur des pétales) avec un seuil de 5.5.
                    - Si inférieur à 5.5 :
                        - On utilise la caractéristique 3 (largeur des pétales) avec un seuil de 1.8.
                            - Si inférieur à 1.8 : classe "versicolor".
                            - Sinon : classe "virginica".
                    - Sinon : classe "virginica".

In [14]:
def build_tree():

  #Racine
  racine = BinaryDecisionTree(feature_index=0, threshold=6.0)


  #1st Enfant
  left_sub_tree = BinaryDecisionTree(feature_index=1, threshold=3.0)
  right_sub_tree = BinaryDecisionTree(feature_index=2, threshold=5.5)

  #2nd Enfant
  left_left_sub_tree = BinaryDecisionTree(feature_index=2, threshold=4.5)
  left_right_sub_tree = BinaryDecisionTree(feature_index=3, threshold=1.8)
  right_right_sub_tree = BinaryDecisionTree(value="virginica")
  right_left_sub_tree = BinaryDecisionTree(value="versicolor")


  #3rd Enfant
  left_left_left_sub_tree = BinaryDecisionTree(value="setosa")
  right_left_left_sub_tree = BinaryDecisionTree(value="versicolor")
  left_left_right_sub_tree = BinaryDecisionTree(value="versicolor")
  right_left_right_sub_tree = BinaryDecisionTree(value="virginica")

  racine.left = left_sub_tree
  racine.right = right_sub_tree

  left_sub_tree.left = left_left_sub_tree
  left_sub_tree.right = right_left_sub_tree
  right_sub_tree.right = right_right_sub_tree
  right_sub_tree.left = left_right_sub_tree

  left_left_sub_tree.left = left_left_left_sub_tree
  left_left_sub_tree.right = right_left_left_sub_tree
  left_right_sub_tree.left = left_left_right_sub_tree
  left_right_sub_tree.right = right_left_right_sub_tree

  return racine



En utilisant la fonction précédente, construire l'arbre de décision et le stocker dans une variable

In [15]:
tree = build_tree()


# Étape 4 : Tester l'arbre sur le dataset IRIS
Faites des prédictions en utilisant l'arbre défini

In [17]:
prediction = tree.predict(X[2])
print(prediction)

versicolor


# Etape 5 : Evaluer l'arbre

Écrivez une fonction `evaluate_tree_performance` qui calcule la précision de l'arbre de décision sur un dataset donné. La précision est définie comme le pourcentage de prédictions correctes.

Exemple d'utilisation :
accuracy = evaluate_tree_performance(tree, iris_data)
print("Précision de l'arbre :", accuracy, "%")

In [19]:
def evaluate_tree_performance(tree, X, Y):
  score = 0
  for i in range(len(Y)):
    print("Caractéristiques : " + str(X[i]) + " Attendu : " + str(Y[i]) + " Predit : " + str(tree.predict(X[i])))
    if Y[i] == tree.predict(X[i]):
      score += 1

  print((score / len(Y)) * 100)

evaluate_tree_performance(tree, X, y)

Caractéristiques : [5.1 3.5 1.4 0.2] Attendu : setosa Predit : versicolor
Caractéristiques : [4.9 3.  1.4 0.2] Attendu : setosa Predit : versicolor
Caractéristiques : [4.7 3.2 1.3 0.2] Attendu : setosa Predit : versicolor
Caractéristiques : [7.  3.2 4.7 1.4] Attendu : versicolor Predit : versicolor
Caractéristiques : [6.4 3.2 4.5 1.5] Attendu : versicolor Predit : versicolor
Caractéristiques : [6.9 3.1 4.9 1.5] Attendu : versicolor Predit : versicolor
Caractéristiques : [6.3 3.3 6.  2.5] Attendu : virginica Predit : virginica
Caractéristiques : [5.8 2.7 5.1 1.9] Attendu : virginica Predit : versicolor
Caractéristiques : [7.1 3.  5.9 2.1] Attendu : virginica Predit : virginica
55.55555555555556
